def hangman(lifes,level):
    if level == 1:
        if lifes == 10:
            print("==========")
            print("|")
            print("|")
            print("|")
            print("|")
            print("|")
            print("|")
            print("======")
        elif lifes < 10 and lifes >= 8:
            print("==========")
            print("|        |")
            print("|        O")
            print("|")
            print("|")
            print("|")
            print("|")
            print("======")
        elif lifes < 8 and lifes >= 6:
            print("==========")
            print("|        |")
            print("|        O")
            print("|       /|")
            print("|")
            print("|")
            print("|")
            print("======")
        elif lifes < 6 and lifes >= 4:
            print("==========")
            print("|        |")
            print("|        O")
            print("|       /|\\")
            print("|")
            print("|")
            print("|")
            print("======")
        elif lifes < 4 and lifes >= 1:
            print("==========")
            print("|        |")
            print("|        O")
            print("|       /|\\")
            print("|       /")
            print("|")
            print("|")
            print("======")
        elif lifes == 0:
            print("==========")
            print("|        |")
            print("|        O")
            print("|       /|\\")
            print("|       / \\")
            print("|")
            print("|")
            print("======")
    elif level == 2:
        if lifes == 5:
            print("==========")
            print("|")
            print("|")
            print("|")
            print("|")
            print("|")
            print("|")
            print("======")
        elif lifes < 5 and lifes >= 4:
            print("==========")
            print("|        |")
            print("|        O")
            print("|")
            print("|")
            print("|")
            print("|")
            print("======")
        elif lifes < 4 and lifes >= 3:
            print("==========")
            print("|        |")
            print("|        O")
            print("|       /|")
            print("|")
            print("|")
            print("|")
            print("======")
        elif lifes < 3 and lifes >= 2:
            print("==========")
            print("|        |")
            print("|        O")
            print("|       /|\\")
            print("|")
            print("|")
            print("|")
            print("======")
        elif lifes < 2 and lifes >= 1:
            print("==========")
            print("|        |")
            print("|        O")
            print("|       /|\\")
            print("|       /")
            print("|")
            print("|")
            print("======")
        elif lifes == 0:
            print("==========")
            print("|        |")
            print("|        O")
            print("|       /|\\")
            print("|       / \\")
            print("|")
            print("|")
            print("======")
    elif level == 3:
        if lifes == 3:
            print("==========")
            print("|")
            print("|")
            print("|")
            print("|")
            print("|")
            print("|")
            print("======")
        elif lifes < 3 and lifes >= 2:
            print("==========")
            print("|        |")
            print("|        O")
            print("|       /|\\")
            print("|")
            print("|")
            print("|")
            print("======")
        elif lifes < 2 and lifes >= 1:
            print("==========")
            print("|        |")
            print("|        O")
            print("|       /|\\")
            print("|       /")
            print("|")
            print("|")
            print("======")
        elif lifes == 0:
            print("==========")
            print("|        |")
            print("|        O")
            print("|       /|\\")
            print("|       / \\")
            print("|")
            print("|")
            print("======")

def lifes(lifes):
    return "\U00002764 " * lifes

if __name__=='__main__':
    print(lifes(20))